baseURL = 'https://enekololo.org/'
locale = 'en-us'
title = 'My Everything Website'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  subtitle = 'The Best Website oat'
  [params.contact]
    email = 'idk'
    phone = 'idk'